### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Keemaaa** [AJaySi/AI-Blog-Writer#1]
hello,
`# python blogen.py
  File "blogen.py", line 7
    from rich import print
                         ^
SyntaxError: invalid syntax`

**Comment by AJaySi** [comment]
Hello,
I will push a new code version today. I do not see the problem locally, so pushing code might solve it.
Note: I need to update requirements.txt also.
Thank you, for reporting this.

**Comment by AJaySi** [comment]
I have pushed a new patch. Please check if it resolves.
Regards.

**Comment by AJaySi** [comment]
Please let me know your usecase or how you will use this tool. I will then get those features ironed out on priority.

**Comment by AJaySi** [comment]
I have updated the README with repl.it option 2. This will help get started quicker on cloud.
