### ISSUE TITLE
Use main_config for easier usage of alwrity

### ISSUE THREAD

**Issue by AJaySi** [AJaySi/AI-Blog-Writer#15]
I am making changes in the code to pick up values defined in main_config.
Presently, its hard coded and main_config will make it easier to choose/modify behavior of program.
WIP.

**Comment by pixelatumente** [comment]
I run the script but don't work:
ModuleNotFoundError: No module named 'lib.gpt_providers.openai_gpt_provider'

**Comment by AJaySi** [comment]
Sorry, I am making changes and wasnt sure if people are using it.
I have uploaded a new patch. Please try with latest code.

Note: Refactoring the code, so expect problems for 2-3 days more. Thanks for your understanding.
