### ISSUE TITLE
 Need Hep regarding "Error occurred while writing to the file"

### ISSUE THREAD

**Issue by A-jmesh** [AJaySi/AI-Blog-Writer#4]
Alwrity is giving 4 amazing blogs. I am getting errors while saving and writing files. The error messages are below:

ERROR|google_serp_search.py:312:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'
ERROR|google_serp_search.py:312:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'

ERROR|tavily_ai_search.py:155:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'

ERROR|tavily_ai_search.py:155:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'

ERROR|metaphor_basic_neural_web_search.py:213:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'

ERROR|google_trends_researcher.py:490:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'
Silhouette Score: 0.10566724694995207

ERROR|google_trends_researcher.py:490:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'

ERROR|google_trends_researcher.py:490:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'
ERROR|google_trends_researcher.py:529:do_google_trends_analysis| Failed to get results from google trends related topics: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ERROR|google_trends_researcher.py:490:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Users\\this\\AI-Blog-Writer\\workspace\\web_research_reports\\Scuba_Diving_in_Goa_2024_Comprehensive_Guide_2024-03-09_21-46-08'

**Comment by AJaySi** [comment]
Check with latest code.

**Comment by A-jmesh** [comment]
Okay, Thank you.
